algo = input(('Digite algo: '))
print(type(algo))
print('É Alfanumérico? ',algo.isalnum())
print('É Alfabético? ',algo.isalpha())
print('É ASCII? ',algo.isascii())
print('É Decimal? ',algo.isdecimal())
print('É um digito? ',algo.isdigit())
print('É identificável? ',algo.isidentifier())
print('É minúsculo? ',algo.islower())
print('É Numérico? ',algo.isnumeric())
print('Pode ser impresso? ',algo.isprintable())
print('É espaço?',algo.isspace())
print('É um titulo? ',algo.istitle())
print('É maiúsculo? ',algo.isupper())